apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortified-crm-fleet
  namespace: fortified-crm-fleet
  annotations:
    iam.gke.io/gcp-service-account: fortified-crm-fleet@agentic-hackerton.iam.gserviceaccount.com
