apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fortified-crm-fleet-secrets
  namespace: fortified-crm-fleet
spec:
  refreshInterval: 0s
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: fortified-crm-fleet-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fortified-crm-fleet
        property: DATABASE_URL
    - secretKey: API_KEY
      remoteRef:
        key: fortified-crm-fleet
        property: API_KEY

